services:
  - type: web
    name: finoerp
    runtime: static
    rootDir: app
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
